name: Build PR

on: pull_request

jobs:
  build-rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo release build
      uses: actions/cache@v1
      with:
        path: target/release
        key: ${{ runner.os }}-cargo-build-target-release-${{ hashFiles('**/Cargo.lock') }}
    - name: Check rust formatting
      run: cargo fmt -- --check
    - name: Run rust tests
      run: cargo test --release --verbose

  build-www:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo release build
        uses: actions/cache@v1
        with:
          path: target/release
          key: ${{ runner.os }}-cargo-build-target-release-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo wasm32 build
        uses: actions/cache@v1
        with:
          path: target/wasm32-unknown-unknown
          key: ${{ runner.os }}-cargo-build-target-wasm32-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install node modules
        run: npm ci
        working-directory: ./www
      - name: Run prettier
        run: npm run prettier:check
        working-directory: ./www
      - uses: cypress-io/github-action@v1
        with:
          build: npm run build --prefix www
          start: npm run serve:dist --prefix www
          working-directory: ./www
