name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build rust
      run: cargo build --verbose
    - name: Run rust tests
      run: cargo test --verbose
    - name: install node modules
      run: npm ci
      working-directory: ./www
    - name: build app
      run: npm run build
      working-directory: ./www
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: www/dist # The folder the action should deploy.
