name: Build PR

on: pull_request

jobs:
  build-rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check rust formatting
      run: cargo fmt -- --check
    - name: Run rust tests
      run: cargo test --release --verbose

  build-www:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install node modules
        run: npm ci
        working-directory: ./www
      - name: Run prettier
        run: npm run prettier:check
        working-directory: ./www
      - uses: cypress-io/github-action@v1
        with:
          build: npm run build --prefix www
          start: npm run serve:dist --prefix www
          working-directory: ./www
