name: Build PR

on: pull_request

jobs:
  build-rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check rust formatting
      run: cargo fmt -- --check
    - name: Run rust tests
      run: cargo test --release --verbose
  build-www:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install node modules
        run: npm ci
        working-directory: ./www
      - name: Build app and wasm
        run: npm run prettier:check
        working-directory: ./www
