name: Test rust crate

on:
  push:
    paths:
      - 'crate-wasm'
      - 'Cargo.lock'
      - 'Cargo.toml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run rust tests
      run: cargo test --release --verbose
